<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="mms"
           tests="1"
           failures="1"
           errors="0"
           skipped="0"
           time="119.998">
  <properties />
            <testcase name="sendSms" time="119.998" classname="mms.MmsTest">
                <failure type="java.lang.AssertionError"
                  message="发送短息失败 expected [2] but found [3]"
              >
<![CDATA[java.lang.AssertionError: 发送短息失败 expected [2] but found [3]
  org.testng.Assert.fail(Assert.java:94)
  org.testng.Assert.failNotEquals(Assert.java:496)
  org.testng.Assert.assertEquals(Assert.java:125)
  org.testng.Assert.assertEquals(Assert.java:372)
  mms.MmsTest.sendSms(MmsTest.java:47)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
  
  
  
</testsuite>
